version: 1.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm test